### ISSUE TITLE
Bug in https version

### ISSUE THREAD

**Issue by nickdataskill** [angeloc/htpdate#3]
Hi

We have cross compiled the code for v1.2.5 using ENABLE_HTTPS on armhf platform

The htpdate program displays an error as follows:

```
# htpdate https://google.com
HTTPS support not compiled in, cannot get timestamp from google.com
No time correction needed
#
```
The program appears to work fine with https apart from the wrong warning message

I'm not a C expert but think that check at lines starting 785 in htpdate.c should probably be surrounded by
```
#ifndef ENABLE_HTTPS
```

Thanks and regards

Nick

**Comment by angeloc** [comment]
@nickdataskill : would you mind opening a PR? ;)
