### ISSUE TITLE
Proxy auth

### ISSUE THREAD

**Issue by hcr2020** [angeloc/htpdate#4]
Hi
Good job maintaining htpdate.
I was unable to connect through proxy. (Using in Openwrt)
Please add support for http proxy authentication with proxy username and password .
Thanks

**Comment by angeloc** [comment]
I don't think it's a so useful feature
* HTTPS is basically unproxable
* For HTTP you can use a generic adapter like proxychains

If you really need the feature and will to sponsor it, let me know!

**Comment by twekkel** [comment]
@hcr2020 @angeloc HTTPS is perfectly proxable, please have a look at upstream https://github.com/twekkel/htpdate where it implemented. (Authentication isn't and probable will never be)
