### ISSUE TITLE
Add support for relative path for the pidfile

### ISSUE THREAD

**Issue by victor-timofei** [angeloc/htpdate#9]
In the example below:
```sh
sudo ./htpdate -D -s -i htp.pid www.wikipedia.org
```
It will create a file in the root directory instead of the directory from which the program was launched.

**Comment by twekkel** [comment]
@victor-timofei  code change was not required.... just start with ${PWD}

./htpdate -D -s -i ${PWD}/htp.pid www.wikipedia.org

**Comment by victor-timofei** [comment]
You can even do:
```bash
${PWD}/htpdate -D -s -i ${PWD}/htp.pid www.wikipedia.org
```
I know it is not essential, but it improves the usability. Many users, including me, expect relative paths to work.
